const colorOptions = {
  orange: {
    PRIMARY_COLOR_FAINT: '#FFF3E0',
    PRIMARY_COLOR_LIGHT: '#FFB74D',
    PRIMARY_COLOR: '#FF9800',
    PRIMARY_COLOR_BOLD: '#EF6C00',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  green: {
    PRIMARY_COLOR_FAINT: '#E8F5E9',
    PRIMARY_COLOR_LIGHT: '#81C784',
    PRIMARY_COLOR: '#4CAF50',
    PRIMARY_COLOR_BOLD: '#2E7D32',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
}

export const base = {
  FONT_SIZE_TINY: 8,
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_EXTRA_LARGE: 24,
  FONT_SIZE_MASSIVE: 34,

  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
}

export const darkTheme = {
  PRIMARY_BACKGROUND_COLOR: '#3d3d3d',
  PRIMARY_BACKGROUND_COLOR_LIGHT: '#797979',

  SECONDARY_BACKGROUND_COLOR: '#ffffff',
  SECONDARY_BACKGROUND_COLOR_LIGHT: '#f7f7f7',

  PRIMARY_TEXT_COLOR: '#ffffff',
  PRIMARY_TEXT_COLOR_LIGHT: '#f7f7f7',
  SECONDARY_TEXT_COLOR: '#3d3d3d',
  PRIMARY_TEXT_BACKGROUND_COLOR: '#3d3d3d',
  SECONDARY_TEXT_BACKGROUND_COLOR: '#ffffff',
  ...colorOptions.green,
}

export const lightTheme = {
  PRIMARY_BACKGROUND_COLOR: '#F0E7D8',
  PRIMARY_BACKGROUND_COLOR_LIGHT: '#f7f7f7',

  SECONDARY_BACKGROUND_COLOR: '#3d3d3d',
  SECONDARY_BACKGROUND_COLOR_LIGHT: '#797979',

  PRIMARY_TEXT_COLOR: '#3d3d3d',
  PRIMARY_TEXT_COLOR_LIGHT: '#797979',
  SECONDARY_TEXT_COLOR: '#ffffff',
  PRIMARY_TEXT_BACKGROUND_COLOR: '#ffffff',
  SECONDARY_TEXT_BACKGROUND_COLOR: '#3d3d3d',
  ...colorOptions.orange,
}
